CREATE DATABASE ACTIVIDAD5

CREATE TABLE VENTA (
IDVENTA INT IDENTITY (1,1) NOT NULL,
FECHAVENTA DATETIME NOT NULL,
TOTALVENTA MONEY NOT NULL,
PRIMARY KEY (IDVENTA),
);

CREATE TABLE PRODUCTO (
IDPRODUCTO INT IDENTITY (1,1) NOT NULL,
NOMBREPRODUCTO NVARCHAR (50) NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
PRIMARY KEY (IDPRODUCTO),
);

CREATE TABLE DETALLEVENTA (
IDDETALLEVENTA INT IDENTITY (1,1) NOT NULL,
IDVENTA INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD  INT NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
TOTALDETALLE MONEY NOT NULL,
PRIMARY KEY (IDDETALLEVENTA),
FOREIGN KEY (IDVENTA) REFERENCES VENTA (IDVENTA),
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO),
);

-- Insertar datos en la tabla VENTA
INSERT INTO VENTA VALUES ('2022-02-01 14:00:00', 6841.00);
INSERT INTO VENTA VALUES ('2022-02-23 13:50:00', 2847.00);
INSERT INTO VENTA VALUES ('2022-03-15 09:20:00', 9189.00);
INSERT INTO VENTA VALUES ('2022-05-20 18:25:00', 5539.00);

-- Insertar datos en la tabla PRODUCTO
INSERT INTO PRODUCTO VALUES ('Leche', 2.50);
INSERT INTO PRODUCTO VALUES ('Pan', 1.25);
INSERT INTO PRODUCTO VALUES ('Huevos', 3.00);
INSERT INTO PRODUCTO VALUES ('Manzanas', 2.99);
INSERT INTO PRODUCTO VALUES ('Arroz', 1.75);
INSERT INTO PRODUCTO VALUES ('Fideos', 1.50);
INSERT INTO PRODUCTO VALUES ('Aceite', 3.99);
INSERT INTO PRODUCTO VALUES ('Azúcar', 2.25);
INSERT INTO PRODUCTO VALUES ('Sal', 0.75);

-- Insertar datos en la tabla DETALLEVENTA
INSERT INTO DETALLEVENTA VALUES (1, 1, 2, 2.50, 5.00);
INSERT INTO DETALLEVENTA VALUES (1, 2, 3, 1.25, 3.75);
INSERT INTO DETALLEVENTA VALUES (2, 3, 1, 3.99, 3.99);
INSERT INTO DETALLEVENTA VALUES (2, 4, 2, 2.99, 5.98);
INSERT INTO DETALLEVENTA VALUES (3, 5, 4, 0.75, 3.00);
INSERT INTO DETALLEVENTA VALUES (4, 2, 1, 1.50, 1.50);
INSERT INTO DETALLEVENTA VALUES (4, 3, 2, 2.25, 4.50);


